service: janken-cafe-backend
frameworkVersion: '3'

provider:
  name: aws
  deploymentMethod: direct	
  profile: serverless-admin
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    CONNECTIONS_TABLE: ${self:service}-connections-${self:provider.stage}
    WEBSOCKET_API_ID: # This will be populated after first deploy or referenced via CloudFormation outputs
      Ref: WebsocketsApi # Reference to the API Gateway WebSocket API created below
    WEBSOCKET_API_ENDPOINT: # Construct the endpoint URL
      Fn::Join:
        - ''
        - - 'https://'
          - Ref: WebsocketsApi
          - '.execute-api.'
          - ${self:provider.region}
          - '.amazonaws.com/'
          - ${self:provider.stage}
  iam: 
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:Query 
          Resource:
            - Fn::GetAtt: [ConnectionsTable, Arn] 
            - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ConnectionsTable}/index/StatePairIdIndex # GSI ARN
        - Effect: Allow
          Action:
            - execute-api:ManageConnections
          Resource:
            - Fn::Join:
              - ':'
              - - arn:aws:execute-api
                - ${self:provider.region}
                - '*' # Account ID
                - ${self:provider.environment.WEBSOCKET_API_ID} # API ID
                - ${self:provider.stage}/POST/@connections/*

functions:
  connect:
    handler: src/functions/connect.handler
    events:
      - websocket:
          route: $connect
  disconnect:
    handler: src/functions/disconnect.handler
    events:
      - websocket:
          route: $disconnect
  defaultHandler:
    handler: src/functions/defaultHandler.handler
    events:
      - websocket:
          route: $default

resources:
  Resources:
    ConnectionsTable: # DynamoDB Table
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.CONNECTIONS_TABLE}
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
          - AttributeName: state
            AttributeType: S # 'WAITING', 'PLAYING'
          - AttributeName: pairId # GSI for finding waiting users easily
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes: # To efficiently find waiting users
          - IndexName: StatePairIdIndex
            KeySchema:
              - AttributeName: state # Partition key for GSI
                KeyType: HASH
              - AttributeName: pairId # Sort key for GSI (use a fixed value like 'NONE' for waiting)
                KeyType: RANGE
            Projection:
              ProjectionType: KEYS_ONLY # Only need connectionId

plugins: 
  - serverless-offline
  - serverless-plugin-typescript

custom: 
  serverless-offline:
    httpPort: 3001 
    websocketPort: 3002
    lambdaPort: 3003